version: '3.5'
services:
  backend:
    image: golang:1.17-alpine3.15
    build:
      context: .
      target: 'build'
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    command: /bin/sh -c "go run main.go"